export const PAGE_DATA_LOADED = 'PageEditor/PAGE_DATA_LOADED';

export const SELECT_SECTION = 'PageEditor/SELECT_SECTION';
export const MOVE_SECTION_UP = 'PageEditor/MOVE_SECTION_UP';
export const MOVE_SECTION_DOWN = 'PageEditor/MOVE_SECTION_DOWN';

export const UNDO = 'PageEditor/UNDO';
export const REDO = 'PageEditor/REDO';

export const GRID_MODE_SWITCH = 'PageEditor/GRID_MODE_SWITCH';

export const SAVE_PAGE_DATA = 'PageEditor/SAVE_PAGE_DATA';
export const SAVE_PAGE_DATA_SUCCESS = 'PageEditor/SAVE_PAGE_DATA_SUCCESS';
export const SAVE_PAGE_DATA_SUCCESS_CLEAR = 'PageEditor/SAVE_PAGE_DATA_SUCCESS_CLEAR';
export const SAVE_PAGE_DATA_ERROR = 'PageEditor/SAVE_PAGE_DATA_ERROR';
export const SAVE_PAGE_DATA_ERROR_CLEAR = 'PageEditor/SAVE_PAGE_DATA_ERROR_CLEAR';

export const SHOW_SECTION_LIST = 'PageEditor/SHOW_SECTION_LIST';
export const HIDE_SECTION_LIST = 'PageEditor/HIDE_SECTION_LIST';
export const ADD_SECTION = 'PageEditor/ADD_SECTION';
export const DELETE_SECTION = 'PageEditor/DELETE_SECTION';

export const SHOW_SECTION_DESIGNS = 'PageEditor/SHOW_SECTION_DESIGNS';
export const HIDE_SECTION_DESIGNS = 'PageEditor/HIDE_SECTION_DESIGNS';
export const CHANGE_SECTION_DESIGN = 'PageEditor/CHANGE_SECTION_DESIGN';

export const SHOW_HYPER_LINK = 'PageEditor/SHOW_HYPER_LINK';
export const HIDE_HYPER_LINK = 'PageEditor/HIDE_HYPER_LINK';
export const SET_HYPER_LINK = 'PageEditor/SET_HYPER_LINK';

export const SHOW_FILE_MANAGER = 'PageEditor/SHOW_FILE_MANAGER';
export const HIDE_FILE_MANAGER = 'PageEditor/HIDE_FILE_MANAGER';
export const CHOOSE_FILE_FROM_FILE_MANAGER = 'PageEditor/CHOOSE_FILE_FROM_FILE_MANAGER';

export const DELETE_IMAGE_COMPONENT = 'PageEditor/DELETE_IMAGE_COMPONENT';

export const TINY_MCE_TEXT_CHANGE = 'PageEditor/TINY_MCE_TEXT_CHANGE';

export const CHANGE_SETTING_DESIGN = 'PageEditor/CHANGE_SETTING_DESIGN';

export const SHOW_SETTING_POPUP = 'PageEditor/SHOW_SETTING_POPUP';
export const HIDE_SETTING_POPUP = 'PageEditor/HIDE_SETTING_POPUP';
export const CHANGE_SETTING_POPUP = 'PageEditor/CHANGE_SETTING_POPUP';

export const CHANGE_SECTION_BACKGROUND = 'PageEditor/CHANGE_SECTION_BACKGROUND';
export const UPDATE_SECTION_BACKGROUND = 'PageEditor/UPDATE_SECTION_BACKGROUND';

export const BUTTON_STYLING_CHANGE = 'PageEditor/BUTTON_STYLING_CHANGE';

export const FLUID_CHANGE = 'PageEditor/FLUID_CHANGE';
